In [4]:
import tensorflow as tf

In [5]:
tf.__version__

'2.1.0'

In [3]:
from tensorflow.keras.models.layers import Dense

ModuleNotFoundError: No module named 'tensorflow.keras.models.layers'

In [6]:
model = tf.keras.models.Sequential()
import math
import random
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas_datareader as web
dataset = web.DataReader("AXISBANK.NS",data_source='yahoo',start='2012-05-07',end='2020-05-11')

In [7]:
dataset

High         Low        Open       Close      Volume  \
Date                                                                     
2012-05-07  205.940002  193.750000  198.000000  204.509995  15244255.0   
2012-05-08  205.979996  194.399994  205.100006  196.690002  12006490.0   
2012-05-09  196.380005  191.000000  194.059998  192.229996  12258880.0   
2012-05-10  198.940002  192.550003  192.550003  196.250000  12281805.0   
2012-05-11  201.800003  193.410004  194.630005  200.039993  12398320.0   
...                ...         ...         ...         ...         ...   
2020-05-05  418.750000  386.500000  414.000000  389.000000  50981056.0   
2020-05-06  394.450012  368.049988  385.000000  388.850006  67511628.0   
2020-05-07  402.250000  382.700012  387.000000  397.350006  41339309.0   
2020-05-08  409.450012  379.649994  403.500000  382.049988  33505509.0   
2020-05-11  393.500000  376.850006  391.000000  379.549988  30141935.0   

             Adj Close  
Date                    
2012-05-07  161.725922  
2012-05-08  155.541901  
2012-05-09  152.014923  
2012-05-10  155.193939  
2012-05-11  158.191055  
...                ...  
2020-05-05  389.000000  
2020-05-06  388.850006  
2020-05-07  397.350006  
2020-05-08  382.049988  
2020-05-11  379.549988  

[1968 rows x 6 columns]

In [8]:
import pandas as pd
train_set = dataset['Low']
train_set = pd.DataFrame(train_set)

In [9]:
train_set

Low
Date                  
2012-05-07  193.750000
2012-05-08  194.399994
2012-05-09  191.000000
2012-05-10  192.550003
2012-05-11  193.410004
...                ...
2020-05-05  386.500000
2020-05-06  368.049988
2020-05-07  382.700012
2020-05-08  379.649994
2020-05-11  376.850006

[1968 rows x 1 columns]

In [10]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
strain_set = sc.fit_transform(train_set)

In [11]:
strain_set

array([[0.06240978],
       [0.06339751],
       [0.0582309 ],
       ...,
       [0.34953731],
       [0.34490252],
       [0.34064767]])

In [12]:
Xtrain = []
Ytrain = []
for i in range(30,1966):
  Xtrain.append(strain_set[i-30:i, 0])
  Ytrain.append(strain_set[i, 0])

Xtrain = np.array(Xtrain)
Ytrain = np.array(Ytrain)
print(Xtrain)

[[0.06240978 0.06339751 0.0582309  ... 0.08406402 0.07365478 0.07494644]
 [0.06339751 0.0582309  0.06058627 ... 0.07365478 0.07494644 0.06886806]
 [0.0582309  0.06058627 0.06189313 ... 0.07494644 0.06886806 0.06669505]
 ...
 [0.49351895 0.36382149 0.41191667 ... 0.4152598  0.43721792 0.37537043]
 [0.36382149 0.41191667 0.39740456 ... 0.43721792 0.37537043 0.35531175]
 [0.41191667 0.39740456 0.22690596 ... 0.37537043 0.35531175 0.3272752 ]]


In [13]:
Xtrain = np.reshape(Xtrain, (Xtrain.shape[0], Xtrain.shape[1], 1) )

In [14]:
Xtrain

array([[[0.06240978],
        [0.06339751],
        [0.0582309 ],
        ...,
        [0.08406402],
        [0.07365478],
        [0.07494644]],

       [[0.06339751],
        [0.0582309 ],
        [0.06058627],
        ...,
        [0.07365478],
        [0.07494644],
        [0.06886806]],

       [[0.0582309 ],
        [0.06058627],
        [0.06189313],
        ...,
        [0.07494644],
        [0.06886806],
        [0.06669505]],

       ...,

       [[0.49351895],
        [0.36382149],
        [0.41191667],
        ...,
        [0.4152598 ],
        [0.43721792],
        [0.37537043]],

       [[0.36382149],
        [0.41191667],
        [0.39740456],
        ...,
        [0.43721792],
        [0.37537043],
        [0.35531175]],

       [[0.41191667],
        [0.39740456],
        [0.22690596],
        ...,
        [0.37537043],
        [0.35531175],
        [0.3272752 ]]])

In [15]:
Ytrain

array([0.06886806, 0.06669505, 0.07017492, ..., 0.35531175, 0.3272752 ,
       0.34953731])

In [16]:
Xtrain.shape

(1936, 30, 1)

In [17]:
Ytrain.shape

(1936,)

In [18]:
Xtest = []
Ytest = []
for i in range(1926, 1936):
  Xtest.append(Xtrain[i])

print(Xtest)

[array([[0.79409486],
       [0.74212468],
       [0.70269117],
       [0.69813238],
       [0.57056244],
       [0.45347761],
       [0.53135686],
       [0.49351895],
       [0.36382149],
       [0.41191667],
       [0.39740456],
       [0.22690596],
       [0.21019041],
       [0.20259244],
       [0.27249382],
       [0.30600087],
       [0.28518244],
       [0.33426535],
       [0.30592491],
       [0.26033705],
       [0.28822163],
       [0.33555702],
       [0.37377482],
       [0.37886548],
       [0.39474527],
       [0.37689002],
       [0.42506116],
       [0.45370554],
       [0.39550506],
       [0.39406143]]), array([[0.74212468],
       [0.70269117],
       [0.69813238],
       [0.57056244],
       [0.45347761],
       [0.53135686],
       [0.49351895],
       [0.36382149],
       [0.41191667],
       [0.39740456],
       [0.22690596],
       [0.21019041],
       [0.20259244],
       [0.27249382],
       [0.30600087],
       [0.28518244],
       [0.33426535],
       [0.

In [19]:
Xtest = np.reshape(Xtest, (10,30,1))

In [20]:
Xtest

array([[[0.79409486],
        [0.74212468],
        [0.70269117],
        [0.69813238],
        [0.57056244],
        [0.45347761],
        [0.53135686],
        [0.49351895],
        [0.36382149],
        [0.41191667],
        [0.39740456],
        [0.22690596],
        [0.21019041],
        [0.20259244],
        [0.27249382],
        [0.30600087],
        [0.28518244],
        [0.33426535],
        [0.30592491],
        [0.26033705],
        [0.28822163],
        [0.33555702],
        [0.37377482],
        [0.37886548],
        [0.39474527],
        [0.37689002],
        [0.42506116],
        [0.45370554],
        [0.39550506],
        [0.39406143]],

       [[0.74212468],
        [0.70269117],
        [0.69813238],
        [0.57056244],
        [0.45347761],
        [0.53135686],
        [0.49351895],
        [0.36382149],
        [0.41191667],
        [0.39740456],
        [0.22690596],
        [0.21019041],
        [0.20259244],
        [0.27249382],
        [0.30600087],
        

In [21]:
for i in range(1926,1936):
  Ytest.append(Ytrain[i])

print(Ytest)

[0.4154117222706113, 0.37772578077966246, 0.38965461208354546, 0.4293920163193242, 0.41525979985380945, 0.43721792213354715, 0.3753704268268647, 0.35531175212642685, 0.3272752028206001, 0.34953730905703384]


In [22]:
Xtrain = np.resize(Xtrain, (1926,30,1))

In [23]:
Xtrain.shape

(1926, 30, 1)

In [24]:
Ytrain = np.resize(Ytrain,(1926))

In [25]:
Ytrain.shape

(1926,)

In [26]:
from tensorflow.keras.layers import LSTM,Dropout,Dense

In [27]:
model.add(LSTM(units = 50, return_sequences = True, input_shape = (30, 1)))
model.add(Dropout(0.2))
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
model.add(LSTM(units = 50, return_sequences = False))
model.add(Dropout(0.2))
model.add(Dense(units = 1
               ))

In [28]:
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [29]:
model.fit(Xtrain, Ytrain, epochs = 150, batch_size = 32)

Train on 1926 samples
Epoch 1/150
1926/1926 [==============================] - 9s 5ms/sample - loss: 0.0323
Epoch 2/150
1926/1926 [==============================] - 5s 2ms/sample - loss: 0.0074
Epoch 3/150
1926/1926 [==============================] - 5s 2ms/sample - loss: 0.0068
Epoch 4/150
1926/1926 [==============================] - 5s 2ms/sample - loss: 0.0060
Epoch 5/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0058
Epoch 6/150
1926/1926 [==============================] - 5s 2ms/sample - loss: 0.0052
Epoch 7/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0049
Epoch 8/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0045
Epoch 9/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0049
Epoch 10/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0041
Epoch 11/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0043
Epoch 12/150
1926/1926 [======

1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0012
Epoch 95/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0011 1s 
Epoch 96/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0011
Epoch 97/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0011
Epoch 98/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0011
Epoch 99/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0011
Epoch 100/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0011
Epoch 101/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 9.6497e-04
Epoch 102/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 9.8227e-04
Epoch 103/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0010
Epoch 104/150
1926/1926 [==============================] - 5s 3ms/sample - loss: 0.0010
Epoch 105/150
1926/1926 [==============

In [52]:
Xtest.shape

(10, 30, 1)

In [57]:
res = model.predict(Xtest)

In [58]:
res

array([[0.39479786],
       [0.4075591 ],
       [0.37706447],
       [0.38912776],
       [0.4181276 ],
       [0.4090303 ],
       [0.42937022],
       [0.37380362],
       [0.35908496],
       [0.32951376]], dtype=float32)

In [63]:
resul = sc.inverse_transform(res)
print(resul)

[[412.48465]
 [420.88242]
 [400.81482]
 [408.7533 ]
 [427.83722]
 [421.85056]
 [435.23566]
 [398.66895]
 [388.98306]
 [369.5231 ]]


In [60]:
Ytest = np.reshape(Ytest, (10,1))

In [61]:
sc.inverse_transform(Ytest)

array([[426.04998779],
       [401.25      ],
       [409.1000061 ],
       [435.25      ],
       [425.95001221],
       [440.3999939 ],
       [399.70001221],
       [386.5       ],
       [368.04998779],
       [382.70001221]])

In [64]:
train_set

Low
Date                  
2012-05-07  193.750000
2012-05-08  194.399994
2012-05-09  191.000000
2012-05-10  192.550003
2012-05-11  193.410004
...                ...
2020-05-05  386.500000
2020-05-06  368.049988
2020-05-07  382.700012
2020-05-08  379.649994
2020-05-11  376.850006

[1968 rows x 1 columns]

In [65]:
strain_set.shape

(1968, 1)

In [85]:
strain_set[1966]

array([0.34490252])

In [68]:
tmrw = []
for i in range(1938, 1968):
    tmrw.append(strain_set[i])

print(tmrw)

[array([0.21019041]), array([0.20259244]), array([0.27249382]), array([0.30600087]), array([0.28518244]), array([0.33426535]), array([0.30592491]), array([0.26033705]), array([0.28822163]), array([0.33555702]), array([0.37377482]), array([0.37886548]), array([0.39474527]), array([0.37689002]), array([0.42506116]), array([0.45370554]), array([0.39550506]), array([0.39406143]), array([0.41541172]), array([0.37772578]), array([0.38965461]), array([0.42939202]), array([0.4152598]), array([0.43721792]), array([0.37537043]), array([0.35531175]), array([0.3272752]), array([0.34953731]), array([0.34490252]), array([0.34064767])]


In [69]:
tmrw = np.reshape(tmrw, (1, 30, 1))

In [70]:
tmrw

array([[[0.21019041],
        [0.20259244],
        [0.27249382],
        [0.30600087],
        [0.28518244],
        [0.33426535],
        [0.30592491],
        [0.26033705],
        [0.28822163],
        [0.33555702],
        [0.37377482],
        [0.37886548],
        [0.39474527],
        [0.37689002],
        [0.42506116],
        [0.45370554],
        [0.39550506],
        [0.39406143],
        [0.41541172],
        [0.37772578],
        [0.38965461],
        [0.42939202],
        [0.4152598 ],
        [0.43721792],
        [0.37537043],
        [0.35531175],
        [0.3272752 ],
        [0.34953731],
        [0.34490252],
        [0.34064767]]])

In [71]:
result = model.predict(tmrw)
print(result)

[[0.34200066]]


In [72]:
print(sc.inverse_transform(result))

[[377.7404]]


In [74]:
tmrw = []
for i in range(1938, 1968):
    tmrw.append(strain_set[i])

tmrw = np.reshape(tmrw, (1, 30, 1))
result = model.predict(tmrw)
print(result)

[[0.34200066]]
[[377.7404]]


In [109]:
#For future 10 days
tmrp = []
start = 1938
for i in range(10):
    tmrp = []
    for j in range(start-1, start+29):
        tmrp.append(strain_set[j])
    tmrp = np.reshape(tmrp ,(1,30,1))
    result = model.predict(tmrp)
    arr = []
    arr.append(result)
    np.append(strain_set, arr)
    start = start+1
    print(sc.inverse_transform(result))
    

[[376.42255]]
[[377.7404]]


IndexError: index 1968 is out of bounds for axis 0 with size 1968

In [111]:
strain_set[1967]

array([0.34064767])

In [89]:
model.save("LowPrice")

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: LowPrice\assets


In [3]:
from keras.models import load_model
model = load_model('LowPrice.h5')

OSError: Unable to open file (unable to open file: name = 'LowPrice.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
newp = []
for i in range(1937,1967):
    newp.append(strain_set[i])
    newp = np.reshape(newp, (1,30,1))
    ajay = model.predict(newp);
    ajay1 = sc.inverse_transform(ajay)
    print(ajay1)

for i in range (1938,1968):
    newp.append(strain_set[i])
    newp = np.reshape(newp, (1,30,1))
    ajay = model.predict(newp);
    ajay1 = sc.inverse_transform(ajay)
    print(ajay1)
    